### ISSUE TITLE
Distributions dependency

### ISSUE THREAD

**Issue by Evizero** [JuliaML/LearnBase.jl#17]
We need to find a better solution to the `params` problem in #14 . LearnBase is not the place to have such a heavy dependency. maybe we can move it closer to the package that needs it @tbreloff ?

**Comment by Evizero** [comment]
Any comments on this?

**Comment by joshday** [comment]
I apparently wasn't watching LearnBase until yesterday, so I missed this.  Maybe StatsBase would be a good home for `params` if JuliaStats would be open to that.

**Comment by tbreloff** [comment]
If this is the only reason for the Distributions dep, then yes I think we
should try to get a method stub into StatsBase. I want to continue to
export it from LearnBase because I want to maintain the generic nature of
the method. We only use the JuliaStats def to avoid clashes.

**Comment by Evizero** [comment]
fixed by #26
