### ISSUE TITLE
Example using LearnBase

### ISSUE THREAD

**Issue by davidbp** [JuliaML/LearnBase.jl#28]
I know JuliaML is in an state of "get your hands dirty" but it would be really nice to have an explanation on how to make a model in a "JuliaML" way. If its not clear, maybe open a discussion on how we would like that to be.

The JuliaML ecosystem is right now focused on providing tools to be used afterwards to create models. There is nevertheless not a single example showing how to use the tools to build a model and how to use the model with the provided tools (MLDataUtils for example).

I would like to do a couple of things:

- port an implementation of a  [Perceptron](https://github.com/davidbp/jml/blob/master/MulticlassPerceptron/source/MulticlassPerceptron.jl)
in such a way that is coherent with the ecosystem. 

- help to build a simple tutorial showing how to use the tools (and the model) in a real (yet it can be tiny) example.

I am doing [tutorials](https://github.com/davidbp/jml/blob/master/notebooks_machine_learning/1_basics.ipynb) for myself but I would like to generate something more readable such as [MLDataPattern documentation](http://mldatapatternjl.readthedocs.io/en/latest/) but I have no idea on how to build this (is it markdown?  I see the extension .rst and I have no idea on how to start building pretty documentation like that).

**Comment by joshday** [comment]
I'm not sure there is a defined "JuliaML way" yet.  JuliaML really doesn't enforce what a model should look like, other than you need to be able to `update!` the `model` from `data`, whatever you decide those things are.  See https://github.com/JuliaML/LearningStrategies.jl 

I have some examples in https://github.com/joshday/SparseRegression.jl/blob/master/src/algorithms.jl 
but that may be a nontrivial introduction.  All SparseRegression does is add a model type and a few learning strategy subtypes and LearningStrategies takes care of everything.

**Comment by joshday** [comment]
This issue also inspired me to write this: https://joshday.github.io/2017/07/13/JuliaML.html

**Comment by davidbp** [comment]
Thank you for your effort, I am looking at SparseRegression to get some inspiration.  I also would like to benchmark your implementations (and my implementation) vs the equivalent algorithm from Scikit-learn.

**Comment by juliohm** [comment]
We are currently revamping some of the JuliaML packages. Thank you for sharing the issue, I will close it for now, and we can get back to it in the future if the planned workflow is still unclear.
