### ISSUE TITLE
Drop support to Julia v1.0?

### ISSUE THREAD

**Issue by juliohm** [JuliaML/LearnBase.jl#37]
The build fails in Julia v1.0. What should we do about it? https://travis-ci.org/github/JuliaML/LearnBase.jl/builds/674968423

If you are ok with it, I can drop support to Julia v1.0 and require Julia >= v1.1 moving forward.

**Comment by johnnychen94** [comment]
I don't think it's a good idea to drop v1.0 support until there's a new LTS Julia version. I believe the test failures can be fixed as commented in https://github.com/JuliaML/LearnBase.jl/pull/36#discussion_r408381119

**Comment by juliohm** [comment]
Thank you @johnnychen94 , I've fixed the issue in the test set. Let's see if it passes now.

**Comment by juliohm** [comment]
Fixed :+1:
