### ISSUE TITLE
LearnBase equivalent for StatsBase.nobs

### ISSUE THREAD

**Issue by Evizero** [JuliaML/LearnBase.jl#5]
For MLDataUtils we need some kind of function that returns how many datapoints are in a dataset. right now I use StatsBase.nobs there. It would be useful to introduce the function here though, since I don't want packages to depend on MLDataUtils just for two function definitions.

As I see it we have three choices
1. Make LearnBase depend on StatsBase, see #1 
2. Define a different `nobs`, which seems like like a recipe for trouble
3. Come up with a new function name.

Thoughts?

cc: @ahwillia @tbreloff @joshday

**Comment by Evizero** [comment]
If 3., I could use some name suggestions

**Comment by ahwillia** [comment]
I'm continually losing this fight, but would like to sync up with StatsBase
better. I'd like to use `fit!` rather than `learn!` which is maybe slightly
beside the point, but it does seem like we are redefining a bunch of
synonyms which is quite bad IMO.

**Comment by Evizero** [comment]
Generally I very much agree, but I just don't see the `fit(::Type{Model},..)` signature working out. That said I am also not going to annoy the StatsBase community with "look, I have problems probably coming up when I eventually get around to implement this and this, please change to my needs". So it is on us to either adapt or diverge.

I see it if we want to use `StatsBase.fit` we do need to make the questionable decision to not use the intended signature `fit(::Type{Model},..)`, which would thus still not really count as "syncing up". But maybe close enough that once we actually have enough hard evidence we could then maybe try to come up with a solution that works for both JuliaStats and JuliaML needs.

**Comment by Evizero** [comment]
I do not have a good answer to this, but I do want to move forward one way or another.

**Comment by Evizero** [comment]
we should put it to a vote, make the decision and live with that for a while.

We have had a lot of interesting and fruitful discussions about this and I think everything has been discussed one way or the other. It is time to get this package on the road, and let it evolve naturally with trial and error.

**Comment by ahwillia** [comment]
But in my use cases it very much makes sense to use that intended signature
for fit. Yet, I still want to use Losses, etc. Hence my predicament.

What are you thinking for the learn signature? How would it differ?

**Comment by Evizero** [comment]
~~I don't actually quite remember. I just had a lot of issues in KSVM.jl trying to make it work and had to go a different way. So the main thing that stuck in memory was frustration (selective memory I suppose). Might have also been lack of Julia experience that lead to my failure.~~  I am willing to try again though. 

Depending on StatsBase may also make for an easier argument for getting this merged into METADATA.

**Comment by Evizero** [comment]
Looking through my old code it was surely related to how SVMs can be specified using different formalism. and the returntype was not of the specified type. For example I can specify an SVM in the C formalism (with this C penalty parameter), which could result, depending on other parameters, in a primal or dual solution

so this would never be true: `typeof(fit(::Type{T}, ...)) <: T`

**Comment by Evizero** [comment]
So it made much more sense for me to have something like `typeof(fit(::MyModelSpecification, ...)) <: MyModelResult`, where the specification can hold parameters specific to that formulation as well

**Comment by Evizero** [comment]
I don't think it would cause any technical problems if we use both signatures side by side, but it might make chaining things together (like tom envisions) somewhat harder. I am ok with going the StatsBase route

EDIT: at this point I really want to just make some progress in approximately the right direction.

**Comment by ahwillia** [comment]
Maybe what you're saying is that we need `learn` and `learn!` _in addition to_ `fit`. This I can certainly get behind. But I would still like to import `StatsBase.fit` and `StatsBase.nobs` and probably other things as well.

Another somewhat annoying thing is that the JuliaStats repos seem under-maintained lately. A few giants aren't moving the same mountains they used to.

**Bottom line:** I have always been in favor of having LearnBase depend on StatsBase. Reexporting a small, curated collection of functions like `nobs` just makes sense to me. I think it is the only logical thing to do seeing as options (2) and (3) introduce conflicts. Option (2) on a literal level, and option (3) on a conceptual level (i.e. users need to learn two APIs that do the same thing but have different names).

The only other option I see is making a 3rd repository `AbstractStats.jl` or something which defines `nobs`, etc. Then have StatsBase and LearnBase separately depend on this. @tbreloff mentioned this at some point.

If this is a feasible solution, I would be on board.

**Comment by Evizero** [comment]
I don't see `AbstractStats.jl` happening short term. But we may be able to present that argument in the future once we have a couple of stable and inter-compatible packages in our ecosystem. As it is now we are too experimental to make this kind of proposals to a well established community.

I find myself agreeing with you on the other points. I just want to get this going so that I can adapt Losses.jl, MLDataUtils.jl, Augmentor.jl, and KSVM.jl accordingly (and get them ready for 0.5 in the process) before I am again swamped with non-julia work.

**Comment by tbreloff** [comment]
If others feel strongly about adding a StatsBase dep short term, then fine.
As long as we're not committing to 'fit(::Type{T}, data...)' as a paradigm
as it just doesn't "fit" well in a continuous/online learning approach.

**Comment by ahwillia** [comment]
> I don't see AbstractStats.jl happening short term. But we may be able to present that argument in the future once we have a couple of stable and inter-compatible packages in our ecosystem

I agree with this. We can always revisit once these packages get more mature.

> As long as we're not committing to 'fit(::Type{T}, data...)' as a paradigm as it just doesn't "fit" well in a continuous/online learning approach.

I'm not saying we should commit to `fit`. In fact, it might be nice to have `learn` for online learning and `fit` for more classic things like regression. Why not support both?

**Comment by Evizero** [comment]
Alright, we'll go with StatsBase then. At least short term. Will surely make METADATA a little easier. I'll make the preparations in the next few days.
