### ISSUE TITLE
Packages that plan to depend on LearnBase in the short term

### ISSUE THREAD

**Issue by Evizero** [JuliaML/LearnBase.jl#6]
For getting this merged into METADATA I would like to present a list of packages that we **know** will depend on LearnBase and derivatives soon after the registration. 
## Already in METADATA
- [JuliaML/MLDataUtils.jl](https://github.com/JuliaML/MLDataUtils.jl)
- [joshday/OnlineStats.jl](https://github.com/joshday/OnlineStats.jl)
## Ready soon
- [JuliaML/Losses.jl](https://github.com/JuliaML/Losses.jl)
- [Evizero/Augmentor.jl](https://github.com/Evizero/Augmentor.jl)
- [tbreloff/Reinforce.jl](https://github.com/tbreloff/Reinforce.jl)
- [JuliaML/MLMetrics.jl](https://github.com/JuliaML/MLMetrics.jl) (wraps some losses)
## In development
- [joshday/SparseRegression.jl](https://github.com/joshday/SparseRegression.jl)
- [JuliaML/Transformations.jl](https://github.com/JuliaML/Transformations.jl)
- [tbreloff/OnlineAI.jl](https://github.com/tbreloff/OnlineAI.jl)
- [JuliaML/Penalties.jl](https://github.com/JuliaML/Penalties.jl)
- [Evizero/KSVM.jl](https://github.com/Evizero/KSVM.jl) (waits for Losses.jl, Penalties.jl and Transformations.jl)

Please adapt the list accordingly. If you are not sure about a specific package, then let us omit it from this list for now.

cc: @tbreloff @ahwillia @joshday

**Comment by tbreloff** [comment]
Transformations
Learn
Reinforce
OnlineAI
OnlineStats (I hope)

As well as anything that depends on these.

**Comment by joshday** [comment]
OnlineStats
SparseRegression

**Comment by Evizero** [comment]
I adapted the list and put the packages in 3 categories. do you agree on those?

**Comment by tbreloff** [comment]
Looks good.  The only change I'd make is to add Reinforce to the "ready soon" list.  (I hope!)

**Comment by tbreloff** [comment]
@Evizero are you taking charge of getting this into metadata?

**Comment by Evizero** [comment]
unless anyone objects, yes

**Comment by Evizero** [comment]
I will do this before monday. I am cleaning up things here and there in the packages we have in this org already, to make sure things go smoothly. I also want to get MLMetrics on the road sooner rather than later

**Comment by Evizero** [comment]
Thinking about adding `MLMetrics` to the list. Its function names are modelled after scikit learn, which I am trying to preserve during my current refactor. metrics of scikit learn also have functions called `hinge_loss` and `log_loss` etc. Might be nice to also offer these signatures to python escapees in `MLMetrics`. The clean way to implement them in my eyes is by wrapping the corresponding losses in `Losses.jl`.

**Comment by joshday** [comment]
You could also add https://github.com/JuliaML/Penalties.jl to the list

**Comment by Evizero** [comment]
I will make the PR to METADATA by the end of tomorrow. I shall spend tomorrow on documentation for `Losses.jl`, since I would like to use that package as a main reference for why it is a good time to get LearnBase registered.

**Comment by Evizero** [comment]
merged into METADATA 🎉

**Comment by joshday** [comment]
Thanks for putting this all together!
